databases:
  - name: maino_connect
    databaseName: maino_connect
    user: maino_connect
    plan: free

services:
  - type: web
    name: maino_connect
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maino_connect
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: MAILER_FROM_ADDRESS
        sync: false
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default